apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "val-backendt"
  annotations:
    argocd/app-name: val-backendt-dev
    backstage.io/kubernetes-id: val-backendt
    backstage.io/kubernetes-namespace: val-backendt-dev
    janus-idp.io/tekton-enabled : 'true'
    github.com/project-slug: 
    quay.io/repository-slug: 
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces/#https://github.com/?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces/#https://github.com/?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/varodrig"
  providesApis:
    - "val-backendt"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "val-backendt"
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/varodrig"
  definition:
    $text: ./openapi.yaml
